Builder for BranchPoints
maliput/maliput_sparse pull request #24
Opened 2022-09-26 11:12 UTC by agalbachicar

# 🎉 New feature

Part of #10

## Summary

Implements the BranchPoint builder.

## Test it

Via unit tests (not yet).

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if it affects the public API)

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

**Note to maintainers**: this PR is in draft state. There are missing tests and it doesn't compile yet but it just aims to show how it would be used for preliminary discussions.

2022-09-26 11:13 UTC, agalbachicar commented
@francocipollone I would appreciate your review on [90ccc36](https://github.com/maliput/maliput_sparse/pull/24/commits/90ccc36ee12c38e8d5249bda4cfa212fde99643e). I am mostly interested in knowing your thoughts on its use.

2022-09-26 13:01 UTC, francocipollone requested changes
lgtm overall.
I agree with the proposed api for the branchpoint building. I left some minor comments.

Populating the branchpoints is something that in general has to be implemented in each backend. I think that having this helper as agnostic to the backend as it is at maliput::base could be beneficial to avoid reimplementing code? Wdyt?

2022-10-10 14:55 UTC, agalbachicar commented
This PR now depends on https://github.com/maliput/maliput/pull/524

2022-10-10 14:55 UTC, agalbachicar commented on include/maliput_sparse/builder/builder.h
> +  void SetBranchPoints(maliput::common::Passkey<BranchPointBuilder>,
Done.

2022-10-10 14:55 UTC, agalbachicar commented on src/builder/builder.cc
> +// Proivdes maliput::api::BranchPointId with an increasing counter to make each ID
Done.

2022-10-10 14:56 UTC, agalbachicar commented on src/builder/builder.cc
> +  int branch_point_count_{0};
Yes but it actually won't go negative until we go over int range. Do you think this is a problem?

2022-10-10 14:57 UTC, agalbachicar commented on src/builder/builder.cc
> +    std::vector<std::unique_ptr<maliput::geometry_base::BranchPoint>>&& branch_points) {
Done.

2022-10-10 14:58 UTC, agalbachicar commented on src/builder/builder.cc
> +            maliput::geometry_base::Lane* lane = segment->lane(j);
Done.

2022-10-10 14:58 UTC, agalbachicar commented on src/builder/builder.cc
> +  const LaneEnd lane_end_b = std::make_pair(lane_id_a, which_b);
Changed the implementation.

2022-10-10 14:58 UTC, agalbachicar commented on src/builder/builder.cc
> +    it_b_side->b_side.insert(a_side_set.begin(), a_side_set.end());
Changed the implementation.

2022-10-11 17:02 UTC, francocipollone approved these changes
LGTM! Nice job! This is a great addition!

2022-10-11 18:32 UTC, agalbachicar commented on test/builder/builder_test.cc
> +  ASSERT_TRUE(lane_end_is_in(lane_a->GetOngoingBranches(finish)->get(2), expected_lane_ends));
You are right. I did not think of it. Let me address that in a follow up PR.

2022-10-11 18:33 UTC, agalbachicar commented on src/builder/builder.cc
> +  auto range_b_a = lane_ends_.equal_range(lane_end_b);
Yes, good catch!

2022-10-11 19:48 UTC, francocipollone approved these changes
:1st_place_medal:

2022-10-12 07:17 UTC, merged