Adds LineString
maliput/maliput_sparse pull request #4
Opened 2022-08-02 14:12 UTC by agalbachicar

# 🎉 Adds LineString

Related to #3

## Summary

Adds the LineString class to support polylines in any coordinate system. They are assumed to be isotropic.

 As part of the discussion of this CL and future CLs we need to define what to do in terms of already compiled template instantiations.

## Test it

## Checklist
- [X] Signed all commits for DCO
- [X] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if it affects the public API)

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-08-02 15:09 UTC, francocipollone requested changes
Thanks for pushing this

2022-08-02 15:09 UTC, francocipollone commented on include/maliput_sample/geometry/line_string.h
> +// }
These convenients methods, perhaps, should be part of another namespace. Actually the `geometry` namespace is a good match for these methods like `BuildCenterLine` or other methods that could come up: GetCurvature, ProjectIn2d, etc. Maybe `LineString` should be lived under `primitives` namespaces and leave the geometry for these methods.

2022-08-02 15:27 UTC, francocipollone commented
> As part of the discussion of this CL and future CLs we need to define what to do in terms of already compiled template instantiations.

Would you like to keep the implementation in the hpp so other instanciations can be extended downstream? I will definitely go for it, Linestring class is simple and it may be beneficial for the user to be able to use any underlying coordinate type.
I'd add some aliases to be used with `maliput::math::Vector3` and `Vector2` 

Respecting to the DistanceFunction I would add a trivial tparam by default.

2022-08-02 16:06 UTC, agalbachicar commented on include/maliput_sample/geometry/line_string.h
> +// }
I intended to send this in a future CL so we could discuss the algorithm in particular.

2022-08-08 09:01 UTC, agalbachicar commented on include/maliput_sample/geometry/line_string.h
> +
Done.

2022-08-08 09:01 UTC, agalbachicar commented
> I'd add some aliases to be used with maliput::math::Vector3 and Vector2

Done

> Respecting to the DistanceFunction I would add a trivial tparam by default.

Done

Thanks @francocipollone

2022-08-08 09:13 UTC, agalbachicar commented
I'll update this PR once #2 is submitted.

2022-08-08 12:12 UTC, francocipollone approved these changes
LGTM

2022-08-08 12:12 UTC, francocipollone commented on include/maliput_sample/geometry/line_string.h
> +/// Defines a polyline in the `CoordinateT` domain composed of M>1 points.
nit; What would be here M?

2022-08-08 13:58 UTC, agalbachicar commented on include/maliput_sample/geometry/line_string.h
> +/// Defines a polyline in the `CoordinateT` domain composed of M>1 points.
Solved.

2022-08-08 14:10 UTC, francocipollone approved these changes
LGTM!

2022-08-08 14:16 UTC, merged