Builds up RoadGeometry out of parsed information.
maliput/maliput_sparse pull request #40
Opened 2022-10-24 19:43 UTC by francocipollone

# 🎉 New feature

Related to https://github.com/maliput/maliput_sparse/issues/34

## Summary

 - Brings Lane and Segment structs from maliput_osm given that they are not backend dependant
 - Creates a RoadGeometry loader that uses the parsed information(Filled up segment structs) and the builder api.
   - This implementation is brought from maliput_osm's road geometry builder as it is not backend dependant.
 - Propose an abstract Parser class that should be implemented by the backends, for parsing the correspondent underlying format and filling up the Lane and Segment structs.

This is a base proposal on https://github.com/maliput/maliput_sparse/issues/34, once this is given the thumbs up the code should be polished, tests should be changed/added and documentation should be added.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if it affects the public API)

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-10-24 19:50 UTC, francocipollone commented
As this is a proposal the code might change, however, the essence will remain, for so, I'd like a general review from you @agalbachicar on this.

The bottom line here is to move up to maliput_sparse all that is not backend dependent and that could easier the life to the backend's creators. In particular https://github.com/maliput/maliput_osm/pull/30 already shows how the implementation can be reduced to mainly just a parser for the underlying format and fill up some segment structs.

2022-10-25 07:09 UTC, agalbachicar requested changes
Some comments for discussion.

2022-10-25 07:09 UTC, agalbachicar commented on include/maliput_sparse/parser/parser.h
> +  const std::unordered_map<Segment::Id, Segment>& GetSegments() const {return DoGetSegments();}
I think it is a bit premature to move things here. This is an example of that. We would likely need also the Junction information and we are not even configuring other RoadNetwork entities (e.g. Intersections, Phases, etc.). The Parser should evolve to to provide all of them most likely.

I would refrain adding this class for the moment.

2022-10-25 07:09 UTC, agalbachicar commented on include/maliput_sparse/parser/lane.h
> +struct Lane {
OSM itself has a width and a set of waypoints instead of a left and right sets. This struct is not generic at a glance.

We are also missing the most complicated cases in which surface information (e.g. CRG files) are provided. There is no support for that in these structs. This point is not a strong argument yet as we are not able to support it in any part of this implementation yet.

2022-10-25 07:09 UTC, agalbachicar commented on include/maliput_sparse/parser/lane.h
> +namespace parser {
Why change it to parser from loader?

2022-10-25 12:47 UTC, francocipollone commented on include/maliput_sparse/parser/lane.h
> +struct Lane {
> This struct is not generic at a glance.

I think that these structs should contain what we can handle with the builder api because at the end of the day the backend's creator must match the information from the parser to the builder. How can we make them even more generic?

2022-10-25 12:49 UTC, francocipollone commented on include/maliput_sparse/parser/lane.h
> +namespace parser {
It was under `maliput_osm/osm`.

2022-12-06 14:04 UTC, francocipollone commented
Now that junctions are populated and the rest of the entities are also added to the road network I moved forwarded and continued this work.

This PR pairs with https://github.com/maliput/maliput_osm/pull/30

@agalbachicar  PTAL

2022-12-06 16:38 UTC, francocipollone commented
Once approved, I will fill up an issue for adding tests for the road network loader here proposed.

2022-12-06 17:53 UTC, agalbachicar requested changes
A few comments to go.

2022-12-06 17:53 UTC, agalbachicar commented on include/maliput_sparse/loader/builder_configuration.h
> +  std::map<std::string, std::string> ToStringMap() const;
I think that we should make these free functions to keep the style of other repositories.
Consider deleting constructors if you want to enforce a specific way of contring from a map this struct.

2022-12-06 17:53 UTC, agalbachicar commented on include/maliput_sparse/loader/road_geometry_loader.h
> +class RoadGeometryLoader {
Nit: missing class docstring.

2022-12-06 17:53 UTC, agalbachicar commented on include/maliput_sparse/parser/lane.h
> +struct Lane {
Perhaps the linestring construction should happen outside this struct. The first time I read this PR, I made a mental model and intent to make this generic for other sparse formats, so restricting at the "parser" level the geometric model when the format is unknown it doesn't sound a good approach to me.

I may be missing context, then I think it's a matter of facing the use case in which another geometry model is required and adapting the code accordingly.

2022-12-06 17:53 UTC, agalbachicar commented on include/maliput_sparse/parser/lane.h
> +  Which end;
Shall we add default values?

2022-12-06 17:53 UTC, agalbachicar commented on include/maliput_sparse/parser/segment.h
> +  Id id;
Add `{}` please.

2022-12-08 13:07 UTC, francocipollone commented on include/maliput_sparse/parser/lane.h
> +  Which end;
Done.

2022-12-08 13:07 UTC, francocipollone commented on include/maliput_sparse/loader/road_geometry_loader.h
> +class RoadGeometryLoader {
Done.

2022-12-12 19:23 UTC, agalbachicar approved these changes
LGTM

2022-12-12 19:24 UTC, agalbachicar commented on include/maliput_sparse/loader/builder_configuration.h
> +  std::map<std::string, std::string> ToStringMap() const;
It's a nit.
The comment was to keep PODs as structs or convert them to classes to have functions like these.

2022-12-12 19:54 UTC, francocipollone commented on include/maliput_sparse/loader/builder_configuration.h
> +  std::map<std::string, std::string> ToStringMap() const;
Ah I see, thanks for the clarification. Let me move forward with this PR and create an issue for improving the style on that.

2022-12-12 19:55 UTC, merged

2022-12-12 19:57 UTC, francocipollone commented on include/maliput_sparse/loader/builder_configuration.h
> +  std::map<std::string, std::string> ToStringMap() const;
https://github.com/maliput/maliput_sparse/issues/44